### ISSUE TITLE
vague, manual requirements

### ISSUE THREAD

**Issue by mungojelly** [hexagrahamaton/soundcube#1]
It isn't clear which versions of the required libraries to install. I'd appreciate a [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) to help me create an appropriate environment.

After making a clean virtualenv with python 2.7.12 and then running "pip install theano" and "pip install keras" I get this output from "python train.py":

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    from lib.net import Net
  File "/home/mungojelly/code/from-github/soundcube/lib/net.py", line 15, in <module>
    import keras.models
  File "/home/mungojelly/.virtualenvs/soundcube2/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/mungojelly/.virtualenvs/soundcube2/lib/python2.7/site-packages/keras/backend/__init__.py", line 67, in <module>
    from .tensorflow_backend import *
  File "/home/mungojelly/.virtualenvs/soundcube2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
```

After then saying "pip install tensorflow" I get this error instead:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    main()
  File "train.py", line 31, in main
    net = Net(Net.TRAIN, autosave=True)
  File "/home/mungojelly/code/from-github/soundcube/lib/net.py", line 64, in __init__
    self.data = utils.load_data(split=self.val_split)
  File "/home/mungojelly/code/from-github/soundcube/lib/utils.py", line 373, in load_data
    return load_all(target_dir, split)[-4:]
  File "/home/mungojelly/code/from-github/soundcube/lib/utils.py", line 355, in load_all
    z = normalize(z)
  File "/home/mungojelly/code/from-github/soundcube/lib/utils.py", line 402, in normalize
    s = s.reshape(shape[0], -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

This project looks interesting, I'm looking forward to trying it out, thanks!

**Comment by hexagontruth** [comment]
Yes your problem I believe is with your ~/.keras/keras.json (or analogous file), which probably has "tensorflow" where it should say "theano." (And I would personally stick with Theano—TensorFlow works, but last I checked required a little fiddling—see http://stackoverflow.com/questions/40046619/keras-tensorflow-gives-the-error-no-attribute-control-flow-ops.) Anyway "theano" was the default when I first wrote that, but they changed it at some point. Which, yes, should probably be documented somewhere. This issue aside though I think it should work with any version of Keras >= 1.0.

Glad to see you are interested in it though FYI if you don't have a GPU and CUDA installed you are in for a slow, slow process.
